services:
  - type: web
    name: timetable-app
    # Remove the 'env: node' line. Render should auto-detect Java.
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/TimetableApp-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod