services:
  - type: web
    name: timetable-app

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: SUPPORT_EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false